version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-runtime:
        dependency-type: production
      npm-development:
        dependency-type: development
  - package-ecosystem: gradle
    directory: /apps/android
    schedule:
      interval: weekly
    groups:
      android-dependencies:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
