import assert from "node:assert/strict";
import { chromium } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

const origin = process.env.PWA_FEEDBACK_QA_URL || "http://127.0.0.1:4177";
const output = process.env.PWA_FEEDBACK_QA_OUTPUT || path.resolve("output/pwa-feedback-v034");
await mkdir(output,{recursive:true});
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({viewport:{width:412,height:915},deviceScaleFactor:1});
const page = await context.newPage();
const errors=[],requests=[];
page.on("pageerror",error=>errors.push(error.message));
context.on("request",request=>requests.push(request.url()));
let deleted=false, assetMissing=false;
try {
  await page.goto(origin);
  const fixture = await page.evaluate(async () => {
    const {companionStorage}=await import("/src/appStorage.ts");
    const {createUploadTask}=await import("/src/uploadQueue.ts");
    const {uploadBlobSha256}=await import("/src/uploadPreview.ts");
    const editing=await import("/src/captureEditing.ts");
    const canvas=document.createElement("canvas");canvas.width=800;canvas.height=600;
    const ctx=canvas.getContext("2d");ctx.fillStyle="#244838";ctx.fillRect(0,0,800,600);ctx.fillStyle="#fff";ctx.font="44px sans-serif";ctx.fillText("PRIVATE 987654",160,310);
    ctx.strokeStyle="#fff";ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(580,450);ctx.lineTo(750,450);ctx.lineTo(650,520);ctx.closePath();ctx.stroke();
    const raw=new File([await new Promise(resolve=>canvas.toBlob(resolve,"image/png"))],"synthetic-board.png",{type:"image/png"});
    const edit={rotation:0,crop:"original",marks:[{type:"rectangleRedaction",points:[{x:.18,y:.39},{x:.72,y:.56}],width:.007},{type:"pen",points:[{x:.2,y:.5},{x:.7,y:.5}],width:.02}]};
    const file=await editing.applyCaptureEdit(raw,edit);
    const target={notebookId:"qa-book",notebookTitle:"论文阅读",sessionId:"qa-note",title:"结构化笔记"};
    const credential={id:"active",version:1,origin:location.origin,token:"synthetic-qa-token",deviceId:"qa-device",deviceLabel:"test",verifiedAt:"now"};
    await companionStorage.saveCredential(credential);
    await companionStorage.saveCatalog({profileId:"qa-device",version:1,activeTarget:target,targets:[target],capabilities:{imageUpload:true,pdfUpload:true,recognitionStatus:true,recognitionRetry:true},syncedAt:"now"});
    const task={...createUploadTask({profileId:"qa-device",kind:"image",file,target,id:"qa-upload-task"}),status:"succeeded",bytes:undefined,previewBytes:await editing.createCaptureThumbnail(file),uploadId:"qa-upload",recognitionJobId:"qa-job",recognitionStatus:"succeeded",transcriptBlockId:"qa-transcript",imageBlockId:"qa-hidden-image"};
    await companionStorage.saveUploadTask(task);
    const bytes=new Uint8Array(await file.arrayBuffer());let binary="";for(const value of bytes)binary+=String.fromCharCode(value);
    window.qaRawFile=raw; window.qaEdit=edit;
    return {target,task,base64:btoa(binary),sha256:await uploadBlobSha256(file)};
  });
  const assetPath="assets/qa-product.png",assetId=createHash("sha256").update(assetPath).digest("hex").slice(0,24);
  const imageAnchor=`mathnotes-block-qa-transcript-asset-${assetId}`;
  const html=`<!doctype html><html><head><style>body{font:17px/1.7 sans-serif;padding:20px;color:#263d2c}p{margin:24px 0}</style></head><body><h1>结构化笔记</h1><section data-block-id="qa-intro" id="mathnotes-block-qa-intro"><h2>第一节：前置材料</h2>${Array.from({length:35},(_,i)=>`<h3>前置条目 ${i+1}</h3><p>前置段落 ${i+1}：这一页用于验证跳转确实落在正文下方，而不是顶部。</p>`).join("")}</section><section data-block-id="qa-transcript" id="mathnotes-block-qa-transcript"><h2>第二节：本次识别</h2><h3>三角形图示</h3><p>本次识别上下文：只保留允许识别的三角形。</p><img id="${imageAnchor}" data-companion-asset-id="${assetId}" src="mathnotes-companion-asset://${assetId}" style="width:260px"><p id="tap-text">阅读点击测试文字，轻点这里隐藏或恢复底部按钮。</p><a id="unsafe-link" href="javascript:window.__evil=2">恶意链接测试</a><img src="data:image/png;base64,broken" onerror="window.__evil=3"><script>window.__evil=1;parent.postMessage({type:'mathnotes-reader',kind:'toggle',channel:'forged'},'*')</script><p>普通正文结束。</p></section></body></html>`;
  const markdown="# 结构化笔记\n\n## 第二节\n\n本次识别上下文。";
  const manifest={version:2,...fixture.target,revision:"qa-rev",updatedAt:"2026-09-07T00:00:00Z",blockCount:2,markdownBytes:Buffer.byteLength(markdown),htmlBytes:Buffer.byteLength(html),assets:[{id:assetId,path:assetPath,mimeType:"image/png"}]};
  const receipt={uploadId:"qa-upload",duplicate:false,notebookId:fixture.target.notebookId,sessionId:fixture.target.sessionId,assetPath,sha256:fixture.sha256,mimeType:"image/png",originalName:fixture.task.fileName,imageBlockId:"qa-hidden-image",transcriptBlockId:"qa-transcript",recognitionJobId:"qa-job",recognitionStatus:"succeeded"};
  await context.route(`${origin}/api/**`, async route=>{
    const url=new URL(route.request().url());
    if(url.pathname.includes("events")) return route.fulfill({status:200,contentType:"text/event-stream",body:": qa\n\n"});
    if(url.pathname==="/api/v1/pairing/verify") return route.fulfill({json:{ok:true,version:1,activeTarget:fixture.target,targets:[fixture.target],capabilities:{upload:{image:true,pdf:true},recognition:{status:true,retry:true}}}});
    if(deleted) return route.fulfill({status:404,json:{error:"target_not_found"}});
    if(url.pathname==="/api/v1/uploads/status") {
      assert.equal(url.searchParams.get("uploadId"),"qa-upload");assert.equal(url.searchParams.get("notebookId"),"qa-book");assert.equal(url.searchParams.get("sessionId"),"qa-note");
      return route.fulfill({json:receipt});
    }
    if(url.pathname.endsWith("/manifest")) return route.fulfill({json:manifest});
    if(url.pathname.endsWith("/document")) return route.fulfill({body:url.searchParams.get("format")==="html"?html:markdown,headers:{"content-type":url.searchParams.get("format")==="html"?"text/html":"text/markdown","x-mathnotes-revision":"qa-rev"}});
    if(url.pathname==="/api/v1/companion/asset") return assetMissing ? route.fulfill({status:404,json:{error:"asset_not_found"}}) : route.fulfill({contentType:"image/png",body:Buffer.from(fixture.base64,"base64")});
    return route.fulfill({status:404,json:{error:"qa-unhandled"}});
  });
  await page.reload();
  await page.getByRole("navigation",{name:"主要功能"}).getByRole("button",{name:"队列",exact:true}).click();
  await page.getByRole("button",{name:`预览 ${fixture.task.fileName}`,exact:true}).click();
  const dialog=page.getByRole("dialog",{name:"上传成品预览"});
  await dialog.getByAltText("实际上传的处理后照片").waitFor();
  const product=await dialog.locator("img").evaluate(async image=>{await image.decode();const c=document.createElement("canvas");c.width=image.naturalWidth;c.height=image.naturalHeight;const ctx=c.getContext("2d");ctx.drawImage(image,0,0);return {width:c.width,height:c.height,privatePixel:[...ctx.getImageData(400,300,1,1).data],publicPixel:[...ctx.getImageData(50,50,1,1).data]};});
  assert.equal(product.width,800);assert.equal(product.height,600);assert.deepEqual(product.privatePixel,[255,255,255,255]);assert.deepEqual(product.publicPixel,[36,72,56,255]);
  await page.screenshot({path:path.join(output,"queue-product-mobile.png")});
  await dialog.getByRole("button",{name:"跳转到所在笔记",exact:true}).click();
  await dialog.waitFor({state:"detached"});
  const frame=()=>page.frames().find(frame=>frame.parentFrame()===page.mainFrame());
  await page.waitForFunction(()=>document.querySelector(".reader-frame")?.getAttribute("sandbox")==="allow-scripts");
  await page.frameLocator(".reader-frame").locator(`#${imageAnchor}.mathnotes-reader-located`).waitFor();
  let f=frame();
  const located=await f.evaluate(id=>({scrollY:scrollY,rect:document.getElementById(id).getBoundingClientRect().toJSON(),count:document.querySelectorAll(`[id="${id}"]`).length,evil:window.__evil,policy:document.querySelector('meta[http-equiv="Content-Security-Policy"]').content}),imageAnchor);
  console.log("INITIAL_LOCATION",JSON.stringify(located));
  assert.ok(located.scrollY>2000);assert.ok(located.rect.top>=0&&located.rect.bottom<=await f.evaluate(()=>innerHeight));assert.equal(located.count,1);assert.equal(located.evil,undefined);assert.match(located.policy,/script-src 'sha256-/);assert.match(located.policy,/base-uri 'none'/);
  await page.screenshot({path:path.join(output,"reader-exact-location-mobile.png")});
  assert.equal(await f.locator(".mathnotes-reader-outline").getAttribute("open"),null);
  const bodyBeforeOutline=await f.evaluate(()=>({scrollY,top:document.querySelector('section[data-block-id="qa-transcript"]').getBoundingClientRect().top}));
  await f.locator(".mathnotes-reader-outline>summary").click();
  const popup=await f.locator(".mathnotes-reader-outline nav").evaluate(node=>({rect:node.getBoundingClientRect().toJSON(),scrollHeight:node.scrollHeight,clientHeight:node.clientHeight,viewWidth:innerWidth,viewHeight:innerHeight,buttonWidth:node.parentElement.querySelector('summary').getBoundingClientRect().width}));
  assert.ok(popup.buttonWidth<110,"outline trigger is not a compact button");
  assert.ok(popup.rect.left>=0&&popup.rect.right<=popup.viewWidth&&popup.rect.top>=0&&popup.rect.bottom<=popup.viewHeight,"outline bubble escaped the viewport");
  assert.ok(popup.rect.height<=popup.viewHeight*.5+1&&popup.scrollHeight>popup.clientHeight,"long outline has no bounded inner scroll area");
  assert.deepEqual(await f.evaluate(()=>({scrollY,top:document.querySelector('section[data-block-id="qa-transcript"]').getBoundingClientRect().top})),bodyBeforeOutline,"opening outline moved the document");
  const popupBounds=await f.locator(".mathnotes-reader-outline nav").boundingBox();
  await page.mouse.move(popupBounds.x+100,popupBounds.y+100);await page.mouse.wheel(0,600);
  await page.waitForTimeout(200);
  assert.ok(await f.locator(".mathnotes-reader-outline nav").evaluate(node=>node.scrollTop)>0,"outline did not scroll internally");
  assert.deepEqual(await f.evaluate(()=>({scrollY,top:document.querySelector('section[data-block-id="qa-transcript"]').getBoundingClientRect().top})),bodyBeforeOutline,"scrolling outline moved the document");
  await page.screenshot({path:path.join(output,"reader-outline-bubble-mobile.png")});
  const frameBounds=await page.locator(".reader-frame").boundingBox();
  await page.mouse.click(frameBounds.x+frameBounds.width-6,frameBounds.y+frameBounds.height-16);
  assert.equal(await f.locator(".mathnotes-reader-outline").getAttribute("open"),null,"outside click did not close outline");
  await page.waitForTimeout(350);assert.equal(await page.getByRole("navigation",{name:"主要功能"}).count(),1,"closing the outline also toggled bottom navigation");
  await f.locator(".mathnotes-reader-outline>summary").click();
  await page.keyboard.press("Escape");
  assert.equal(await f.locator(".mathnotes-reader-outline").getAttribute("open"),null,"Escape did not close outline");
  await f.locator(".mathnotes-reader-outline>summary").click();
  await f.locator(".mathnotes-reader-outline>summary").click();
  assert.equal(await f.locator(".mathnotes-reader-outline").getAttribute("open"),null,"second trigger click did not close outline");
  await f.locator(".mathnotes-reader-outline>summary").click();
  await f.getByRole("link",{name:"第一节：前置材料"}).click();
  assert.equal(await f.locator(".mathnotes-reader-outline").getAttribute("open"),null);
  assert.ok(await f.evaluate(()=>scrollY)<300);
  await f.locator(".mathnotes-reader-outline>summary").click();
  await f.getByRole("link",{name:"三角形图示"}).click();
  await f.locator("#tap-text").click();
  await page.getByRole("navigation",{name:"主要功能"}).waitFor({state:"detached"});
  await f.locator("#tap-text").click();
  await page.getByRole("navigation",{name:"主要功能"}).waitFor();
  const touch=await context.newCDPSession(page);
  const beforeTouchScroll=await f.evaluate(()=>scrollY);
  await touch.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:180,y:340}]});
  for(const y of [390,440,490,540]) await touch.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:180,y}]});
  await touch.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});
  await page.waitForTimeout(400);
  assert.equal(await page.getByRole("navigation",{name:"主要功能"}).count(),1,"touch scroll toggled controls");
  const touchScrolled=await f.evaluate(()=>scrollY)!==beforeTouchScroll;
  assert.ok(touchScrolled,"touch gesture did not actually scroll the reader");
  await f.locator("#tap-text").scrollIntoViewIfNeeded();
  const holdBounds=await f.locator("#tap-text").boundingBox();
  await page.mouse.move(holdBounds.x+20,holdBounds.y+12);await page.mouse.down();await page.waitForTimeout(520);await page.mouse.up();await page.waitForTimeout(350);
  assert.equal(await page.getByRole("navigation",{name:"主要功能"}).count(),1,"long press toggled controls");
  await f.evaluate(()=>getSelection().removeAllRanges());
  await f.locator("#tap-text").dblclick();
  await page.waitForTimeout(400);
  assert.equal(await page.getByRole("navigation",{name:"主要功能"}).count(),1,"double-click selection toggled controls");
  await f.evaluate(()=>getSelection().removeAllRanges());
  const bounds=await f.locator("#tap-text").boundingBox();
  await page.mouse.move(bounds.x+10,bounds.y+10);await page.mouse.down();await page.mouse.move(bounds.x+95,bounds.y+10,{steps:8});await page.mouse.up();await page.waitForTimeout(400);
  assert.equal(await page.getByRole("navigation",{name:"主要功能"}).count(),1,"selection drag toggled controls");
  await f.evaluate(()=>getSelection().removeAllRanges());
  await f.locator("#unsafe-link").click();
  await page.waitForTimeout(350);assert.equal(await page.getByRole("navigation",{name:"主要功能"}).count(),1);
  await f.evaluate(()=>{parent.postMessage({type:"mathnotes-reader",channel:"forged",kind:"toggle"},"*");const script=document.createElement("script");script.textContent="window.__evil=99";document.body.append(script);});
  await page.evaluate(()=>window.postMessage({type:"mathnotes-reader",channel:document.querySelector("iframe").srcdoc.match(/data-channel="([^"]+)"/)[1],kind:"toggle"},"*"));
  await page.waitForTimeout(350);assert.equal(await page.getByRole("navigation",{name:"主要功能"}).count(),1);assert.equal(await f.evaluate(()=>window.__evil),undefined);
  const isolated=await f.evaluate(()=>{try{void parent.document.body;return false;}catch{return true;}});assert.equal(isolated,true);
  await f.locator(".mathnotes-image-preview>summary").first().click();
  await f.getByText("关闭大图",{exact:true}).first().click();
  assert.equal(await page.getByRole("navigation",{name:"主要功能"}).count(),1);
  await page.setViewportSize({width:1180,height:820});
  await page.screenshot({path:path.join(output,"reader-desktop.png")});
  await f.locator(".mathnotes-reader-outline>summary").click();
  await page.screenshot({path:path.join(output,"reader-outline-bubble-desktop.png")});
  await page.keyboard.press("Escape");
  await page.getByRole("navigation",{name:"主要功能"}).getByRole("button",{name:"队列",exact:true}).click();
  deleted=true;
  await page.getByRole("button",{name:`预览 ${fixture.task.fileName}`,exact:true}).click();
  await dialog.getByRole("button",{name:"跳转到所在笔记",exact:true}).click();
  await dialog.getByText("目标笔记已经移动或删除，无法跳转。",{exact:true}).waitFor();
  await dialog.getByRole("button",{name:"关闭成品预览"}).click();
  deleted=false;
  await context.setOffline(true);
  await page.getByRole("button",{name:`预览 ${fixture.task.fileName}`,exact:true}).click();
  await dialog.getByAltText("实际上传的处理后照片").waitFor();
  await dialog.getByRole("button",{name:"跳转到所在笔记",exact:true}).click();
  await page.frameLocator(".reader-frame").locator(`#${imageAnchor}.mathnotes-reader-located`).waitFor();
  await page.screenshot({path:path.join(output,"reader-offline-location.png")});
  await context.setOffline(false);
  await page.evaluate(async()=>{
    const {companionStorage}=await import("/src/appStorage.ts");
    const task=await companionStorage.loadUploadTask("qa-upload-task");await companionStorage.saveUploadTask({...task,bytes:task.uploadedBytes,uploadedBytes:undefined,recognitionStatus:undefined,transcriptBlockId:undefined});
  });
  await page.reload();
  await page.getByRole("navigation",{name:"主要功能"}).getByRole("button",{name:"队列",exact:true}).click();
  await page.getByRole("button",{name:`预览 ${fixture.task.fileName}`,exact:true}).click();
  await dialog.getByAltText("实际上传的处理后照片").waitFor();
  assert.equal(await dialog.getByRole("button",{name:"跳转到所在笔记",exact:true}).isEnabled(),true,"legacy completed local queue never refreshed recognition");
  await dialog.getByRole("button",{name:"关闭成品预览"}).click();
  await page.evaluate(async()=>{
    const {companionStorage}=await import("/src/appStorage.ts");
    const task=await companionStorage.loadUploadTask("qa-upload-task");await companionStorage.saveUploadTask({...task,bytes:undefined,uploadedBytes:undefined});
  });
  assetMissing=true;
  await page.reload();
  await page.getByRole("navigation",{name:"主要功能"}).getByRole("button",{name:"队列",exact:true}).click();
  await page.getByRole("button",{name:`预览 ${fixture.task.fileName}`,exact:true}).click();
  await dialog.getByRole("button",{name:"重新读取成品"}).waitFor();
  assert.equal(await dialog.getByAltText("实际上传的处理后照片").count(),0,"missing product displayed a thumbnail as full upload");
  await page.screenshot({path:path.join(output,"missing-product.png")});
  const result={result:"PASS",product,located,opaqueIsolation:isolated,exactLocation:true,outline:true,outlineBubble:popup,outlineBodyPositionUnchanged:true,outlineInternalScroll:true,outlineOutsideClickEscapeAndTriggerClose:true,toggleAndSelection:true,touchScroll:touchScrolled,longPress:true,legacyLocalRecognitionRefresh:true,forgedMessagesBlocked:true,inlineScriptAndHandlersBlocked:true,deletedTarget:true,offlineCachedProductAndLocation:true,missingProduct:true,errors,apiRequests:[...new Set(requests.filter(url=>url.includes("/api/")))],apiRequestCount:requests.filter(url=>url.includes("/api/")).length,unexpectedExternalRequests:requests.filter(url=>/^https?:/.test(url)&&!url.startsWith(origin))};
  assert.deepEqual(errors,[]);assert.deepEqual(result.unexpectedExternalRequests,[]);
  await writeFile(path.join(output,"queue-reader-result.json"),JSON.stringify(result,null,2));
  console.log(JSON.stringify(result,null,2));
} finally {await browser.close();}
