import { _electron as electron } from "playwright";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

const root = process.cwd();
const fixture = await mkdtemp(path.join(tmpdir(), "mathnotes-polish-"));
const output = path.join(root, "output/playwright/windows-polish");
await mkdir(output, { recursive: true });
const app = await electron.launch({ args: ["--no-stdio-init", path.join(root, "apps/windows/electron-dist/main.cjs"), `--user-data-dir=${path.join(fixture, "profile")}`], chromiumSandbox: false, cwd: root, env: { ...process.env, MATHNOTES_ROOT: path.join(fixture, "notes"), MATHNOTES_DEV_SERVER: "" } });
try {
  const page = await app.firstWindow();
  page.setDefaultTimeout(12_000);
  await page.waitForSelector("[data-testid=session-source-editor] .cm-editor");
  console.log("reader ready");
  const current = await page.evaluate(() => window.mathNotes.loadCurrentSession());
  const editor = page.locator("[data-testid=source-block-editor] .cm-content").first();
  await editor.click();
  await page.keyboard.press("Control+End");
  await page.keyboard.type(" UNSAVED_RENAME_CHECK");
  await page.getByRole("button", { name: "笔记目录", exact: true }).first().click();
  await page.locator(".recent-reading-row").first().click({ button: "right" });
  await page.getByRole("menuitem", { name: "重命名", exact: true }).click();
  await page.getByTestId("session-title-prompt").getByRole("textbox").fill("最近阅读重命名验证");
  await page.getByRole("button", { name: "保存名称", exact: true }).click();
  await page.waitForFunction(async () => (await window.mathNotes.loadRecentSessions())[0]?.title === "最近阅读重命名验证", undefined, { timeout: 12000 });
  console.log("recent rename ready");
  assert.match(await editor.innerText(), /UNSAVED_RENAME_CHECK/, "Renaming must preserve unsaved source edits");
  await page.getByRole("button", { name: "笔记目录", exact: true }).first().click();
  await page.getByTestId("notebook-drawer").getByText("最近阅读重命名验证", { exact: true }).waitFor();
  await page.locator(".recent-reading-row").first().click({ button: "right" });
  await page.getByRole("menuitem", { name: "删除", exact: true }).click();
  await page.getByTestId("session-delete-confirm").getByText("最近阅读重命名验证", { exact: true }).waitFor();
  await page.getByRole("button", { name: "取消删除", exact: true }).click();
  assert.equal((await page.evaluate(() => window.mathNotes.loadCurrentSession())).sessionId, current.sessionId);
  console.log("delete confirmation ready");
  const blockIds = await page.locator("[data-testid=source-block]").evaluateAll((items) => items.map((item) => item.dataset.blockId));
  const moving = blockIds.at(-1);
  const target = blockIds[0];
  const header = page.locator(`[data-testid=source-block][data-block-id="${moving}"] [data-testid=source-block-header]`);
  await header.scrollIntoViewIfNeeded();
  const box = await header.boundingBox();
  await page.mouse.move(box.x + 50, box.y + box.height / 2);
  await page.mouse.down();
  const nativeMove = page.mouse.move(box.x + 80, box.y + box.height / 2 - 20, { steps: 6 });
  await page.getByTestId("block-reorder-preview").waitFor();
  console.log("drag preview ready");
  assert.equal(await page.locator(".block-reorder-card").count(), blockIds.length);
  const destination = page.locator(`.block-reorder-card[data-block-id="${target}"]`);
  await destination.scrollIntoViewIfNeeded();
  const targetBox = await destination.boundingBox();
  await page.mouse.move(targetBox.x + 100, targetBox.y + 8, { steps: 8 });
  await page.mouse.move(targetBox.x + 101, targetBox.y + 9);
  await page.screenshot({ path: path.join(output, "drag-preview.png") });
  await page.mouse.up();
  await nativeMove;
  await page.getByTestId("block-reorder-preview").waitFor({ state: "detached" });
  await page.waitForFunction((id) => document.querySelector("[data-testid=source-block]")?.getAttribute("data-block-id") === id, moving, { timeout: 12000 });
  const reordered = await page.evaluate(() => window.mathNotes.loadCurrentSession());
  assert.equal(reordered.sourceDocument.markdownBlocks[0].blockId, moving);
  const targetSession = await page.evaluate(async (notebookId) => window.mathNotes.createSession({ notebookId }), current.notebookId);
  await page.locator("[data-testid=source-block-header]").first().click({ button: "right" });
  await page.getByRole("button", { name: "多选块", exact: true }).click();
  await page.getByRole("button", { name: "复制到…", exact: true }).click();
  await page.getByRole("button", { name: "目标笔记", exact: true }).click();
  const list = page.getByRole("listbox", { name: "目标笔记" });
  await list.waitFor();
  assert.equal(await list.evaluate((element) => getComputedStyle(element).borderRadius), "14px");
  await page.waitForFunction(() => getComputedStyle(document.querySelector("[data-testid=block-transfer-dialog]")).opacity === "1");
  await page.screenshot({ path: path.join(output, "rounded-target.png"), animations: "disabled" });
  await page.keyboard.press("Escape");
  await page.getByTestId("block-transfer-dialog").getByRole("button", { name: "取消", exact: true }).last().click();
  await writeFile(path.join(output, "result.json"), JSON.stringify({ fixture, rename: true, deleteConfirmation: true, dragReorder: true, compactPreviews: blockIds.length, roundedTarget: true, targetSessionId: targetSession.sessionId }, null, 2));
  console.log("PASS Windows recent rename/delete confirmation, real native drag to distant block, compact previews, rounded target picker");
} catch (error) {
  const page = app.windows()[0];
  await page?.screenshot({ path: path.join(output, "failure.png") }).catch(() => undefined);
  console.log(await page?.locator("body").innerText());
  throw error;
} finally { await app.close(); }
