import { createHash } from "node:crypto";

export const COMPANION_READER_STYLE = `:root{color-scheme:light dark;--page:#faf9f5;--paper:#fffefd;--ink:#23231f;--muted:#625f58;--line:#e5e1d8;--code:#f1f0eb;--quote:#a9bfb4;--error:#a24d43;--warning-bg:#f8f1df;--warning-line:#dfd3b8;--warning-ink:#665d49}*{box-sizing:border-box}html,body{width:100%;max-width:100%;overflow-x:hidden}body{margin:0;padding:18px 16px 40px;background:var(--page);color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,"Noto Sans SC",sans-serif;font-size:17px;line-height:1.72;letter-spacing:0}.session-title,.note-block,h1,h2,h3,h4,p,li,blockquote{min-width:0;max-width:100%;overflow-wrap:anywhere;word-break:normal;white-space:normal}.session-title{margin:0 0 14px;font-size:clamp(23px,6vw,28px);line-height:1.28}.note-block{padding:14px 2px;border-top:1px solid var(--line)}.note-block:first-of-type{border-top:0}.pdf-block{display:grid;gap:3px;padding:12px;border:1px solid var(--line);border-radius:7px;background:var(--paper)}.pdf-block span{color:var(--muted);font-size:14px}h1,h2,h3,h4{line-height:1.32;margin:10px 0 12px}p{margin:9px 0}ul,ol{max-width:100%;padding-left:1.5em}blockquote{margin:12px 0;padding-left:13px;border-left:3px solid var(--quote);color:var(--muted)}pre{max-width:100%;overflow-x:auto;padding:12px;background:var(--code);border-radius:6px;white-space:pre-wrap;overflow-wrap:anywhere}code{font-family:"Cascadia Mono","SFMono-Regular",Consolas,monospace}.math-inline{display:inline-block;max-width:100%;vertical-align:-.12em}.math-display{width:100%;max-width:100%;margin:14px 0;overflow-x:auto;overflow-y:hidden;text-align:center;-webkit-overflow-scrolling:touch}.math-display math[display="block"]{display:block;width:max-content;min-width:100%;margin:0}.math-display .katex-display,.math-display .katex-display>.katex,.math-display .katex-display>.katex>.katex-html{width:max-content;min-width:100%}@media(max-width:640px){.math-display .katex-display>.katex>.katex-html>.tag{position:sticky;right:0;display:block;width:max-content;min-width:3.5em;margin:.4em 0 0 auto;text-align:right}}table{display:block;width:100%;max-width:100%;overflow-x:auto;border-collapse:collapse;-webkit-overflow-scrolling:touch}img,svg,video,canvas{display:block;max-width:100%;height:auto;margin:12px auto;border-radius:6px}.katex svg{max-width:none;height:inherit;margin:0;border-radius:0}.math-error{color:var(--error)}.asset-sync-warning{margin:16px 0 0;padding:10px 12px;border:1px solid var(--warning-line);border-radius:6px;background:var(--warning-bg);color:var(--warning-ink);font-size:14px}@media(prefers-color-scheme:dark){:root{--page:#171916;--paper:#20231f;--ink:#f1f1ec;--muted:#aaa99f;--line:#41453f;--code:#292c28;--quote:#72c59f;--error:#e09a91;--warning-bg:#332d20;--warning-line:#655638;--warning-ink:#dfc992}}`;

const PARSED_STYLE_TEXT = `\n${COMPANION_READER_STYLE}\n`;

export const COMPANION_READER_STYLE_CSP_HASH = `sha256-${createHash("sha256")
  .update(PARSED_STYLE_TEXT)
  .digest("base64")}`;
