import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, expect, it } from "vitest";
import { BlockStore } from "./blockStore";
import { SessionAiRevisionService } from "./sessionAiRevision";
import { buildMarkdownContext } from "./assistantTask";
const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))); });
it("passes intact continuation context and applies raw unlocked fragments without touching locked ones", async () => {
  const root = await mkdtemp(join(tmpdir(), "mathnotes-continuation-ai-")); roots.push(root);
  const store = new BlockStore(root);
  const target = { notebookId: "n", sessionId: "s" };
  await store.createSession({ ...target, title: "公式拆分", now: "2026-09-08T00:00:00Z" });
  const pieces = ["说明\n$$\\frac{", "x", "}{y}$$\n"];
  for (const markdown of pieces) await store.appendMarkdownBlock({ ...target, source: "user", markdown, now: "2026-09-08T00:00:00Z" });
  const session = await store.readSession("n", "s");
  session.blocks.forEach(block => { block.continuationGroup = "g"; });
  session.blocks[1].status = "locked";
  const sessionDir = store.getSessionDir("n", "s");
  for (const [index, block] of session.blocks.entries()) await writeFile(join(sessionDir, block.path), pieces[index]);
  await writeFile(join(sessionDir, "session.json"), JSON.stringify(session));
  const service = new SessionAiRevisionService(store, async () => ({ name: "mock", async assist(input) {
    expect(input.intent).toBe("session_edit");
    const context = JSON.parse(input.markdownContext);
    expect(context.continuations[0].markdown).toBe(pieces.join(""));
    expect(context.continuations[0].blocks[1]).toEqual({ blockId: "0002", locked: true });
    expect(context.continuationInstructions).toContain("不要对单个片段 trim");
    return { markdown: JSON.stringify({ summary: "修改说明", changes: [{ blockId: "0001", markdown: "新说明\n$$\\frac{", summary: "仅修改说明" }, { blockId: "0002", markdown: "z", summary: "想替换分子" }], lockedSuggestions: [] }) };
  } }));
  const proposal = await service.propose({ ...target, instruction: "更新说明" });
  expect(proposal.changes).toHaveLength(1);
  expect(proposal.lockedSuggestions[0].blockId).toBe("0002");
  await service.apply({ ...target, proposalId: proposal.id });
  expect(await store.readMarkdownBlock("n", "s", "0001")).toBe("新说明\n$$\\frac{");
  expect(await store.readMarkdownBlock("n", "s", "0002")).toBe("x");
  expect((await store.readSession("n", "s")).blocks.map(block => block.continuationGroup)).toEqual(["g", "g", "g"]);
  const context = buildMarkdownContext({ focus: { kind: "block", blockId: "0002", label: "固定分子", excerpt: "x" }, readableBlocks: session.blocks, markdownByBlockId: new Map(session.blocks.map((block, index) => [block.id, pieces[index]])) });
  expect(context).toContain(JSON.stringify(pieces.join("")));
  expect(context).toContain("已锁定片段原文不可改变");
  expect(await readFile(join(sessionDir, session.blocks[1].path), "utf8")).toBe("x");
});
